# Assignment 3

## Task 1, Question 1

Write a function to compute 5/0 and use try/except to catch the exceptions.

In [8]:
def my_compute(a,b):
    try:
        print(a/b)
    except ZeroDivisionError:
        print(ZeroDivisionError,'Divide by Zero Error Occured')

In [9]:
my_compute(5,0)

<class 'ZeroDivisionError'> Divide by Zero Error Occured


## Task 1, Question 2

Implement a Python program to generate all sentences where subject is in ["Americans","Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

Hint: Subject,Verb and Object should be declared in the program as shown below.

subjects=["Americans ","Indians"] 

verbs=["play","watch"] 

objects=["Baseball","Cricket"] 

In [11]:
subjects=["Americans","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]
for i in subjects:
    for j in verbs:
        for k in objects:
            print(i+' '+j+' '+k)

Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


## Task 2, Question 1

Write a function so that the columns of the output matrix are powers of the input vector.The order of the powers is determined by the increasing boolean argument.Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

In [17]:
import numpy as np

def my_matrix(lists,n=None,increasing=False):
    ls = np.array(lists)
    print(np.vander(lists,n,increasing))

In [18]:
my_matrix([1,2,3,4],4,True)

[[ 1  1  1  1]
 [ 1  2  4  8]
 [ 1  3  9 27]
 [ 1  4 16 64]]


In [21]:
my_matrix([1,2,3,5])

[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [125  25   5   1]]
